<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchimage</name>
   <tag></tag>
   <elementGuidId>cdd8b407-eedd-48b6-bfc4-ff895e1b6f2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;content&quot;]/div[2]/main/div[4]/div/div[1]/div[2]/h4/a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;content&quot;]/div[2]/main/div[4]/div/div[1]/div[2]/h4/a</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//img[@src='/medias/sys_master/images/images/h43/hf7/10854335971358.jpg']</value>
   </webElementXpaths>
</WebElementEntity>
