<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>afterpayok</name>
   <tag></tag>
   <elementGuidId>9f445cdc-8462-453d-b5a0-502d8afaff15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/section[2]/section/form/div/payment-schedule/section/due-today/section/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/section[2]/section/form/div/payment-schedule/section/due-today/section/div/div[2]/button</value>
   </webElementProperties>
</WebElementEntity>
