<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>afterpaypassword</name>
   <tag></tag>
   <elementGuidId>d3834b8f-56a0-47fc-aa46-c5f435c8ced5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/section[2]/section/form/div[2]/div/input[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/section[2]/section/form/div[2]/div/input[2]</value>
   </webElementProperties>
</WebElementEntity>
