<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>editamount</name>
   <tag></tag>
   <elementGuidId>c53137b2-ff50-4ac7-bb62-bd940f8f63a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;paymentGiftCardPanel&quot;]/div/div[2]/div/div[4]/div[2]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;paymentGiftCardPanel&quot;]/div/div[2]/div/div[4]/div[2]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
