<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gctextamt</name>
   <tag></tag>
   <elementGuidId>ca95b58c-8b97-4378-9f25-60de7cb228d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;paymentGiftCardPanel&quot;]/div/div[2]/div/div[3]/div[2]/span[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;paymentGiftCardPanel&quot;]/div/div[2]/div/div[3]/div[2]/span[2]/input</value>
   </webElementProperties>
</WebElementEntity>
