<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>gcupdate</name>
   <tag></tag>
   <elementGuidId>1679e24d-1fdf-48dc-b419-b2269e8015ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;paymentGiftCardPanel&quot;]/div/div[2]/div/div[4]/div[2]/input[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;paymentGiftCardPanel&quot;]/div/div[2]/div/div[4]/div[2]/input[2]</value>
   </webElementProperties>
</WebElementEntity>
