<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>remove</name>
   <tag></tag>
   <elementGuidId>93dfbf9a-8413-4138-87d2-b35f9d804ba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;paymentGiftCardPanel&quot;]/div/div[2]/div/div[5]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;paymentGiftCardPanel&quot;]/div/div[2]/div/div[5]/div[2]/a</value>
   </webElementProperties>
</WebElementEntity>
